### ISSUE TITLE
There is an autocompletion problem on PhpStorm.

### ISSUE THREAD

**Issue by neyaoz** [mp911de/atsoundtrack#10]
There is no problem if I haven't started to type yet when I want to use autocomplete:
![image](https://cloud.githubusercontent.com/assets/4792515/21571242/f31da326-ceff-11e6-84aa-65931e459066.png)

But If I have already typed "@" it looks different, (actually it is not a problem, but it is a sign that makes me feel like there is something wrong at somewhere):
![image](https://cloud.githubusercontent.com/assets/4792515/21571239/e7d09fdc-ceff-11e6-9836-ef278d3a24b6.png)

And If I continue to typing, the suggestion is not appearing anymore:
![image](https://cloud.githubusercontent.com/assets/4792515/21571265/333e0522-cf00-11e6-8f5b-1681850303f0.png)
![image](https://cloud.githubusercontent.com/assets/4792515/21571270/41f7f9ec-cf00-11e6-8c7a-00e2003301c3.png)

**Comment by mp911de** [comment]
That's fixed now.

**Comment by neyaoz** [comment]
Would you mind to publish an update?
I do not know how to compile source files.

Thank you,

**Comment by mp911de** [comment]
Done.
