### ISSUE TITLE
I can't get this working in IntelliJ or PHPStorm on OSX

### ISSUE THREAD

**Issue by gavinwilliams** [mp911de/atsoundtrack#8]
I've been trying to get this to work for years but it never does. In the preferences pane I get "Cannot provide @soundtrack" in the examples section.

<img width="778" alt="screen shot 2016-04-30 at 13 20 08" src="https://cloud.githubusercontent.com/assets/611832/14935805/5db01484-0ed6-11e6-8031-27192767f1e1.png">

**Comment by mp911de** [comment]
Hi @gavinwilliams,
thanks for your bug report. Which player (iTunes, Spotify) do you use? 
Please note that the example view does not update in real-time if tracks start/stop. It just updates if you switch settings. You might want to start a track and then open the preferences.

**Comment by gavinwilliams** [comment]
Hey @mp911de. I'm using iTunes. Even whilst I'm listening to something it doesn't update. Using @soundtrack also doesn't work.

**Comment by mp911de** [comment]
Can you check the IntelliJ logs for errors related to @soundtrack?
The plugin uses AppleScript to retrieve the data from iTunes (and Spotify). It runs in particular:

```
osascript -e 'tell application "iTunes" to get current stream title'
```

and 

```
osascript -e 'tell application "iTunes"
if exists name of current track then
get name of current track
end if
end tell'
```

Could you run these commands in your terminal to verify AppleScript works for you?

**Comment by mp911de** [comment]
Closing the ticket because of inactivity.
