### ISSUE TITLE
$soundtrack variable on the other predefined templates?

### ISSUE THREAD

**Issue by neyaoz** [mp911de/atsoundtrack#9]
$soundtrack variable is only accessible on "PHP File Header". Is it possible to make accessible on following templates:

PHP Class Doc Comment
PHP Function Doc Comment
PHP Interface Doc Comment
PHP Field Doc Comment

Also on settings variables should be extended like ${time}¹ etc. Some of date/time definitions are already defined on "PHP File Header", but not on the others.

**Comment by mp911de** [comment]
Adding the `$soundtrack` variable is only possible for file templates but not class/function/field docs. That's a limitation of the IntelliJ PHP plugin.
